### ISSUE TITLE
[1week] 주제 계획

### ISSUE THREAD

**Issue by ByeongminLee** [Team-Stuckyi/Stuckyi-TechCamp#1]
## 1week (2022.01.03~2022.01.12) 

1월 12일 수요일 발표할 주제에 대해 이슈를 남겨주세요.

**Comment by abcabcp** [comment]
cookie & web storage

**Comment by 0x000613** [comment]
SQL Injection & XSS

**Comment by cksals3753** [comment]
linear Data Structure

**Comment by heejj1206** [comment]
OSI 7 Layer
